# Generated by Django 4.2.11 on 2026-06-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('days_past_due', models.IntegerField()),
                ('amount_owed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prior_payment_behavior', models.CharField(max_length=255)),
                ('hardship_indicator', models.BooleanField(default=False)),
                ('preferred_channel', models.CharField(max_length=50)),
            ],
        ),
    ]
