# Generated by Django 4.2.11 on 2026-06-17 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='borrower_docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg'])]),
        ),
    ]
