# Generated by Django 4.2.11 on 2026-06-17 09:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strategy', '0002_borrower_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrower',
            options={'ordering': ['-days_past_due']},
        ),
        migrations.AddField(
            model_name='borrower',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, help_text='The agent responsible for this borrower.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_borrowers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrower',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrower',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='borrower_docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('agent', 'Agent'), ('supervisor', 'Supervisor')], default='agent', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
